language: python

matrix:
  include:
    - python: 2.7
      env:
        - COVERAGE=false
        - TESTERS="pytest"
        - ARGS="--mpl --verbose"
    - python: 3.4
      env:
        - COVERAGE=false
        - TESTERS="pytest"
        - ARGS="--mpl --verbose"
    - python: 3.5
      env:
        - COVERAGE=false
        - TESTERS="pytest"
        - ARGS="--mpl --verbose"
    - python: 3.6
      env:
        - COVERAGE=true
        - TESTERS="pytest coverage"
        - ARGS="--mpl --verbose --cov"

# Install, update, and setup Miniconda
# This should not need changing.
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  # - export PATH="$HOME/miniconda/bin:$PATH"
  - . $HOME/miniconda/etc/profile.d/conda.sh
  - conda update --yes conda

# We just set up a conda environment with the right Python version.
# This should not need changing.
install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION nomkl numpy matplotlib
  - conda activate test
  - conda install --yes --channel=conda-forge ${TESTERS}
  - pip install pytest-mpl>=0.8
  - if [ ${COVERAGE} = true ]; then
      pip install pytest-cov>=2.5
      pip install codecov
  - pip install .

script:
  - python check_lsys.py ${ARGS}

after_success:
  - if [ ${COVERAGE} = true ]; then
      coverage report -m;
      codecov;
    fi
