language: python

matrix:
  include:
    - python: 2.7
      env:
        - COVERAGE=false
        - TESTERS="pytest"
        - ARGS="--mpl --verbose"
    - python: 3.4
      env:
        - COVERAGE=false
        - TESTERS="pytest"
        - ARGS="--mpl --verbose"
    - python: 3.5
      env:
        - COVERAGE=false
        - TESTERS="pytest"
        - ARGS="--mpl --verbose"
    - python: 3.6
      env:
        - COVERAGE=true
        - TESTERS="pytest coverage"
        - ARGS="--mpl --verbose --cov"

# Install, update, and setup Miniconda
# This should not need changing.
before_install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

# We just set up a conda environment with the right Python version.
# This should not need changing.
install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION nomkl numpy matplotlib
  - source activate test
  - conda install --yes --channel=conda-forge ${TESTERS}
  - pip install pytest-mpl>=0.8
  - if [ ${COVERAGE} = true ]; then
      pip install pytest-cov>=2.5;
      pip install codecov;
    fi
  - pip install .

script:
  - python check_lsys.py ${ARGS}

after_success:
  - if [ ${COVERAGE} = true ]; then
      coverage report -m;
      codecov;
    fi
