name: Lint

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Linters
        run: |
          pip install -U pip
          pip install black isort
      - name: Run Linters
        run: |
          black ./lsys --check --diff
          isort ./lsys --check --diff
